data_file = 'public/data.json'
public_dir = 'public'
qr_dir = 'public/qr'

[verifier]
name = 'Novasama Technologies'
public_key = '16d5a6266345874d8f5b7f88a6619711b2829b52b2865826b1ecefb62beef34f'

[[chains]]
name = 'statemine'
title = 'Statemine'
color = '#113911'
icon = 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/gradient/Statemine.svg'
rpc_endpoints = [
    'wss://statemine.api.onfinality.io/public-ws',
    'wss://statemine-rpc.dwellir.com',
    'wss://statemine-rpc.polkadot.io',
]
testnet = false
