data_file = 'public/data_dev.json'
public_dir = 'public'
qr_dir = 'public/qr'

[verifier]
name = 'Novasama Technologies'
public_key = '16d5a6266345874d8f5b7f88a6619711b2829b52b2865826b1ecefb62beef34f'

[[chains]]
name = 'westmint'
title = 'Westmint'
color = '#77bb77'
icon = 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/gradient/Westmint_Testnet.svg'
rpc_endpoints = [
    'wss://westmint-rpc.polkadot.io',
    'wss://westmint-rpc.dwellir.com',
]
testnet = true
