data_file = "public/data.json"
public_dir = "public"
qr_dir = "public/qr"

[verifier]
name = "Novasama Technologies"
public_key = "16d5a6266345874d8f5b7f88a6619711b2829b52b2865826b1ecefb62beef34f"

[[chains]]
name = "bifrost"
title = "Bifrost"
color = "#5a25f0"
logo = "Bifrost_Kusama.svg"
rpc_endpoints = ["wss://bifrost-parachain.api.onfinality.io/public-wss", "wss://bifrost-rpc.liebi.com/wss", "wss://bifrost-rpc.dwellir.com"]
genesis_hash = "0x9f28c6a68e0fc9646eff64935684f6eeeece527e37bbe1f213d22caa1d9d6bed"

[[chains]]
name = "acala"
title = "Acala"
color = "#645AFF"
logo = "Acala.svg"
rpc_endpoints = ["wss://acala-rpc.dwellir.com_1", "wss://acala-rpc-1.aca-api.networkcom_1", "wss://acala-rpc-2.aca-api.network/wscom_1", "wss://acala-rpc-3.aca-api.network/wscom_1", "wss://acala.polkawallet.iocom_1", "wss://acala-polkadot.api.onfinality.io/public-wscom_1"]
genesis_hash = "0xfc41b9bd8ef8fe53d58c7ea67c794c7ec9a73daf05e6d54b14ff6342c99ba64c"
