name: Verify

on:
  pull_request:
    branches:
      - master
    paths:
      - 'public/qr/**'
      - 'config.toml'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v3

      - uses: ./.github/workflows/rust-install

      - name: ⚙ Build metadata-cli
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: ⚙ Run verifier
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --release -- -c=config.toml verify

      - name: ⚙ Run verifier dev
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --release -- -c=config_dev.toml verify
