name: Verify

on:
  pull_request:
    branches:
      - master
    paths:
      - 'public/qr/**'
      - 'config.toml'

jobs:
  verify:
    runs-on: ubuntu-20.04
    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v4

      - uses: ./.github/workflows/rust-install

      - name: ⚙ Run verifier
        run: cargo run --release -- verify